# Generated by Django 4.1.5 on 2024-07-05 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=50)),
                ('room_address', models.IntegerField()),
                ('village_address', models.CharField(max_length=50)),
                ('city_address', models.CharField(max_length=50)),
                ('state_address', models.CharField(max_length=50)),
                ('pincode_address', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('alt_phone', models.IntegerField()),
            ],
        ),
    ]
